//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Robot.JobEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDP.Robot.JobEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFolder {
            get {
                object obj = ResourceManager.GetObject("IcoFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TDPRobot {
            get {
                object obj = ResourceManager.GetObject("TDPRobot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while triggering the task..
        /// </summary>
        internal static string TxtAnErrorOccurredTriggeringTask {
            get {
                return ResourceManager.GetString("TxtAnErrorOccurredTriggeringTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving.
        /// </summary>
        internal static string TxtAnErrorOccurredWhileSaving {
            get {
                return ResourceManager.GetString("TxtAnErrorOccurredWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dummy Programmer Robot.
        /// </summary>
        internal static string TxtApplicationName {
            get {
                return ResourceManager.GetString("TxtApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cut and paste objects in the same folder..
        /// </summary>
        internal static string TxtCannotCutAndPasteSameFolder {
            get {
                return ResourceManager.GetString("TxtCannotCutAndPasteSameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TxtCopy {
            get {
                return ResourceManager.GetString("TxtCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        internal static string TxtCreateFolder {
            get {
                return ResourceManager.GetString("TxtCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string TxtCut {
            get {
                return ResourceManager.GetString("TxtCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs data not loaded correctly.
        /// </summary>
        internal static string TxtDataNotLoadedCorrectly {
            get {
                return ResourceManager.GetString("TxtDataNotLoadedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TxtDelete {
            get {
                return ResourceManager.GetString("TxtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items?.
        /// </summary>
        internal static string TxtDeleteSelectedItems {
            get {
                return ResourceManager.GetString("TxtDeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close the application?.
        /// </summary>
        internal static string TxtDoYouReallyWantToCloseApplication {
            get {
                return ResourceManager.GetString("TxtDoYouReallyWantToCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} between {2} and {3}.
        /// </summary>
        internal static string TxtDynamicDataBetween {
            get {
                return ResourceManager.GetString("TxtDynamicDataBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} contains {2}.
        /// </summary>
        internal static string TxtDynamicDataContains {
            get {
                return ResourceManager.GetString("TxtDynamicDataContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} ends with {2}.
        /// </summary>
        internal static string TxtDynamicDataEndsWith {
            get {
                return ResourceManager.GetString("TxtDynamicDataEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} equals {2}.
        /// </summary>
        internal static string TxtDynamicDataEquals {
            get {
                return ResourceManager.GetString("TxtDynamicDataEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} greater than {2}.
        /// </summary>
        internal static string TxtDynamicDataGreaterThan {
            get {
                return ResourceManager.GetString("TxtDynamicDataGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} less than {2}.
        /// </summary>
        internal static string TxtDynamicDataLessThan {
            get {
                return ResourceManager.GetString("TxtDynamicDataLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} starts with {2}.
        /// </summary>
        internal static string TxtDynamicDataStartsWith {
            get {
                return ResourceManager.GetString("TxtDynamicDataStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clearing log files.
        /// </summary>
        internal static string TxtErrorWhileClearingLogs {
            get {
                return ResourceManager.GetString("TxtErrorWhileClearingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the log file.
        /// </summary>
        internal static string TxtErrorWhileOpeningLogFile {
            get {
                return ResourceManager.GetString("TxtErrorWhileOpeningLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} ({1}) doesn&apos;t execute.
        /// </summary>
        internal static string TxtExecCondObjectDoesNotExecute {
            get {
                return ResourceManager.GetString("TxtExecCondObjectDoesNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} ({1}) executes.
        /// </summary>
        internal static string TxtExecCondObjectExecutes {
            get {
                return ResourceManager.GetString("TxtExecCondObjectExecutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string TxtFieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("TxtFieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid integer.
        /// </summary>
        internal static string TxtFieldNotContainAValidInteger {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string TxtFolder {
            get {
                return ResourceManager.GetString("TxtFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max value.
        /// </summary>
        internal static string TxtMaxValue {
            get {
                return ResourceManager.GetString("TxtMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min value.
        /// </summary>
        internal static string TxtMinValue {
            get {
                return ResourceManager.GetString("TxtMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number between &quot;{0}&quot; and &quot;{1}&quot;.
        /// </summary>
        internal static string TxtMustBeANumberBetweenXAndY {
            get {
                return ResourceManager.GetString("TxtMustBeANumberBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string TxtObject {
            get {
                return ResourceManager.GetString("TxtObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} ({1}) doesn&apos;t execute.
        /// </summary>
        internal static string TxtObjectDoesNotExecute {
            get {
                return ResourceManager.GetString("TxtObjectDoesNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object don&apos;t execute.
        /// </summary>
        internal static string TxtObjectDontExecute {
            get {
                return ResourceManager.GetString("TxtObjectDontExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object executes.
        /// </summary>
        internal static string TxtObjectExecutes {
            get {
                return ResourceManager.GetString("TxtObjectExecutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TxtPaste {
            get {
                return ResourceManager.GetString("TxtPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One ore more plugins were not loaded correctly.
        /// </summary>
        internal static string TxtPluginsNotLoadedCorrectly {
            get {
                return ResourceManager.GetString("TxtPluginsNotLoadedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        internal static string TxtProperties {
            get {
                return ResourceManager.GetString("TxtProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string TxtRename {
            get {
                return ResourceManager.GetString("TxtRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string TxtRoot {
            get {
                return ResourceManager.GetString("TxtRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dummy Programmer Robot.
        /// </summary>
        internal static string TxtTheDummyProgrammerRobot {
            get {
                return ResourceManager.GetString("TxtTheDummyProgrammerRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors, cannot save the configuration..
        /// </summary>
        internal static string TxtThereAreSomeErrors {
            get {
                return ResourceManager.GetString("TxtThereAreSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be greater than field &quot;{0}&quot;.
        /// </summary>
        internal static string TxtThisFieldCannotBeGreaterThanField {
            get {
                return ResourceManager.GetString("TxtThisFieldCannotBeGreaterThanField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string TxtTrigger {
            get {
                return ResourceManager.GetString("TxtTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to trigger the selected task?.
        /// </summary>
        internal static string TxtTriggerSelectedTaskQuestion {
            get {
                return ResourceManager.GetString("TxtTriggerSelectedTaskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string TxtValue {
            get {
                return ResourceManager.GetString("TxtValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value between.
        /// </summary>
        internal static string TxtValueBetween {
            get {
                return ResourceManager.GetString("TxtValueBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains.
        /// </summary>
        internal static string TxtValueContains {
            get {
                return ResourceManager.GetString("TxtValueContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ends with.
        /// </summary>
        internal static string TxtValueEndsWith {
            get {
                return ResourceManager.GetString("TxtValueEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value equals to.
        /// </summary>
        internal static string TxtValueEqualsTo {
            get {
                return ResourceManager.GetString("TxtValueEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value greater than.
        /// </summary>
        internal static string TxtValueGreaterThan {
            get {
                return ResourceManager.GetString("TxtValueGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value less than.
        /// </summary>
        internal static string TxtValueLessThan {
            get {
                return ResourceManager.GetString("TxtValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value starts with.
        /// </summary>
        internal static string TxtValueStartsWith {
            get {
                return ResourceManager.GetString("TxtValueStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string TxtWorkspace {
            get {
                return ResourceManager.GetString("TxtWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace root.
        /// </summary>
        internal static string TxtWorkspaceRoot {
            get {
                return ResourceManager.GetString("TxtWorkspaceRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name.
        /// </summary>
        internal static string TxtYouMustEnterAName {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an execution condition.
        /// </summary>
        internal static string TxtYouMustEnterAnExecCondition {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAnExecCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an item..
        /// </summary>
        internal static string TxtYouMustSelectItem {
            get {
                return ResourceManager.GetString("TxtYouMustSelectItem", resourceCulture);
            }
        }
    }
}
