//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Robot.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDP.Robot.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} between {2} and {3}.
        /// </summary>
        internal static string TxtDynamicDataBetween {
            get {
                return ResourceManager.GetString("TxtDynamicDataBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} contains {2}.
        /// </summary>
        internal static string TxtDynamicDataContains {
            get {
                return ResourceManager.GetString("TxtDynamicDataContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} ends with {2}.
        /// </summary>
        internal static string TxtDynamicDataEndsWith {
            get {
                return ResourceManager.GetString("TxtDynamicDataEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} equals {2}.
        /// </summary>
        internal static string TxtDynamicDataEquals {
            get {
                return ResourceManager.GetString("TxtDynamicDataEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} greater than {2}.
        /// </summary>
        internal static string TxtDynamicDataGreaterThan {
            get {
                return ResourceManager.GetString("TxtDynamicDataGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} less than {2}.
        /// </summary>
        internal static string TxtDynamicDataLessThan {
            get {
                return ResourceManager.GetString("TxtDynamicDataLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0}, dynamic data {1} starts with {2}.
        /// </summary>
        internal static string TxtDynamicDataStartsWith {
            get {
                return ResourceManager.GetString("TxtDynamicDataStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default recordset.
        /// </summary>
        internal static string TxtDynDataDefaultRecordset {
            get {
                return ResourceManager.GetString("TxtDynDataDefaultRecordset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date.
        /// </summary>
        internal static string TxtDynDataExecutionEndDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (day).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateDay {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (hour).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateHour {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (minute).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateMinute {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (month).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateMonth {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (second).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateSecond {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (ticks).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateTicks {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateUnderscore {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (only date, separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateUnderscoreDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateUnderscoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (only time, separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateUnderscoreTime {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateUnderscoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date (year).
        /// </summary>
        internal static string TxtDynDataExecutionEndDateYear {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution result.
        /// </summary>
        internal static string TxtDynDataExecutionResult {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution return value.
        /// </summary>
        internal static string TxtDynDataExecutionReturnValue {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date.
        /// </summary>
        internal static string TxtDynDataExecutionStartDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (day).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateDay {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (hour).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateHour {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (minute).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateMinute {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (month).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateMonth {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (second).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateSecond {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (ticks).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateTicks {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateUnderscore {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (only date, separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateUnderscoreDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateUnderscoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (only time, separated by underscores).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateUnderscoreTime {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateUnderscoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date (year).
        /// </summary>
        internal static string TxtDynDataExecutionStartDateYear {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field X of recordset&apos;s row.
        /// </summary>
        internal static string TxtDynDataFieldXOfRecordsetsRow {
            get {
                return ResourceManager.GetString("TxtDynDataFieldXOfRecordsetsRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of iterations.
        /// </summary>
        internal static string TxtDynDataNumberOfIterations {
            get {
                return ResourceManager.GetString("TxtDynDataNumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        internal static string TxtDynDataObjectID {
            get {
                return ResourceManager.GetString("TxtDynDataObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        internal static string TxtDynDataObjectName {
            get {
                return ResourceManager.GetString("TxtDynDataObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string TxtFieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("TxtFieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a number between &quot;{1}&quot; and &quot;{2}&quot;.
        /// </summary>
        internal static string TxtMustBeANumberBetweenXAndY {
            get {
                return ResourceManager.GetString("TxtMustBeANumberBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} ({1}) doesn&apos;t execute.
        /// </summary>
        internal static string TxtObjectDoesNotExecute {
            get {
                return ResourceManager.GetString("TxtObjectDoesNotExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} ({1}) executes.
        /// </summary>
        internal static string TxtObjectExecutes {
            get {
                return ResourceManager.GetString("TxtObjectExecutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dummy Programmer Robot.
        /// </summary>
        internal static string TxtTheDummyProgrammerRobot {
            get {
                return ResourceManager.GetString("TxtTheDummyProgrammerRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors, cannot save configuration..
        /// </summary>
        internal static string TxtThereAreSomeErrors {
            get {
                return ResourceManager.GetString("TxtThereAreSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an iteration mode.
        /// </summary>
        internal static string TxtYouMustChooseAnIterationMode {
            get {
                return ResourceManager.GetString("TxtYouMustChooseAnIterationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a dynamic data.
        /// </summary>
        internal static string TxtYouMustSelectADynamicData {
            get {
                return ResourceManager.GetString("TxtYouMustSelectADynamicData", resourceCulture);
            }
        }
    }
}
