//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDP.Robot.Plugins.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDP.Robot.Plugins.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoCpuEvent32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoCpuEvent32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoDateTimeEventImg32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoDateTimeEventImg32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoDiskImg32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoDiskImg32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoExcel32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoExcel32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFolder32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoFolder32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFolderEvent32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoFolderEvent32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoFtpSftp32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoFtpSftp32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoMail32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoMail32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoMemoryEvent32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoMemoryEvent32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoReadTextFile32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoReadTextFile32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoRESTApi32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoRESTApi32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoRunProgram32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoRunProgram32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSqlServerBackup32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoSqlServerBackup32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSqlServerBulkCopy32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoSqlServerBulkCopy32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSqlServerQuery32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoSqlServerQuery32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoSystemEvents32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoSystemEvents32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoTDPRobot32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoTDPRobot32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoUnzip32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoUnzip32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoWriteTextFile32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoWriteTextFile32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IcoZip32x32 {
            get {
                object obj = ResourceManager.GetObject("IcoZip32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightningAdd {
            get {
                object obj = ResourceManager.GetObject("LightningAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / overwrite files in the archive.
        /// </summary>
        internal static string TxtAddOrOverwriteFilesInTheArchive {
            get {
                return ResourceManager.GetString("TxtAddOrOverwriteFilesInTheArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the file.
        /// </summary>
        internal static string TxtAnErrorOccurredWhileProcessingTheFile {
            get {
                return ResourceManager.GetString("TxtAnErrorOccurredWhileProcessingTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append row.
        /// </summary>
        internal static string TxtAppendRow {
            get {
                return ResourceManager.GetString("TxtAppendRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least a field among days, hours or minutes must be greater than 0.
        /// </summary>
        internal static string TxtAtLeastOneFieldMustDaysHoursMinBeGreaterThan0 {
            get {
                return ResourceManager.GetString("TxtAtLeastOneFieldMustDaysHoursMinBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag &quot;Is identity&quot; cannot be set to true for datatypes String and DateTime.
        /// </summary>
        internal static string TxtCannotSetIsDentity {
            get {
                return ResourceManager.GetString("TxtCannotSetIsDentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change this option the configuration in &quot;Column definition&quot; tab will be lost. Do you want to continue?.
        /// </summary>
        internal static string TxtChangingThisOptionYouWillLoseColumnDef {
            get {
                return ResourceManager.GetString("TxtChangingThisOptionYouWillLoseColumnDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress backup.
        /// </summary>
        internal static string TxtCompressBackup {
            get {
                return ResourceManager.GetString("TxtCompressBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TxtCopy {
            get {
                return ResourceManager.GetString("TxtCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpu event.
        /// </summary>
        internal static string TxtCpuEvent {
            get {
                return ResourceManager.GetString("TxtCpuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create with unique names.
        /// </summary>
        internal static string TxtCreateWithUniqueNames {
            get {
                return ResourceManager.GetString("TxtCreateWithUniqueNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date start.
        /// </summary>
        internal static string TxtDateStart {
            get {
                return ResourceManager.GetString("TxtDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        internal static string TxtDatetime {
            get {
                return ResourceManager.GetString("TxtDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / Time event.
        /// </summary>
        internal static string TxtDateTimeEvent {
            get {
                return ResourceManager.GetString("TxtDateTimeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string TxtDecimal {
            get {
                return ResourceManager.GetString("TxtDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TxtDelete {
            get {
                return ResourceManager.GetString("TxtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted files.
        /// </summary>
        internal static string TxtDeletedFiles {
            get {
                return ResourceManager.GetString("TxtDeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        internal static string TxtDeleteRow {
            get {
                return ResourceManager.GetString("TxtDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space event.
        /// </summary>
        internal static string TxtDiskSpaceEvent {
            get {
                return ResourceManager.GetString("TxtDiskSpaceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not compress backup.
        /// </summary>
        internal static string TxtDoNotCompressBackup {
            get {
                return ResourceManager.GetString("TxtDoNotCompressBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change type.
        /// </summary>
        internal static string TxtDynDataChangeType {
            get {
                return ResourceManager.GetString("TxtDynDataChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpu usage %.
        /// </summary>
        internal static string TxtDynDataCpuUsagePercentage {
            get {
                return ResourceManager.GetString("TxtDynDataCpuUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default recordset.
        /// </summary>
        internal static string TxtDynDataDefaultRecordset {
            get {
                return ResourceManager.GetString("TxtDynDataDefaultRecordset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk name.
        /// </summary>
        internal static string TxtDynDataDiskName {
            get {
                return ResourceManager.GetString("TxtDynDataDiskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space (bytes).
        /// </summary>
        internal static string TxtDynDataDiskSpaceByte {
            get {
                return ResourceManager.GetString("TxtDynDataDiskSpaceByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution end date.
        /// </summary>
        internal static string TxtDynDataExecutionEndDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution result.
        /// </summary>
        internal static string TxtDynDataExecutionResult {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution return value.
        /// </summary>
        internal static string TxtDynDataExecutionReturnValue {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution start date.
        /// </summary>
        internal static string TxtDynDataExecutionStartDate {
            get {
                return ResourceManager.GetString("TxtDynDataExecutionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field X of recordset&apos;s row.
        /// </summary>
        internal static string TxtDynDataFieldXOfRecordsetsRow {
            get {
                return ResourceManager.GetString("TxtDynDataFieldXOfRecordsetsRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension.
        /// </summary>
        internal static string TxtDynDataFileExtension {
            get {
                return ResourceManager.GetString("TxtDynDataFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string TxtDynDataFileName {
            get {
                return ResourceManager.GetString("TxtDynDataFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name without extension.
        /// </summary>
        internal static string TxtDynDataFileNameWithoutExtension {
            get {
                return ResourceManager.GetString("TxtDynDataFileNameWithoutExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File full path and name.
        /// </summary>
        internal static string TxtDynDataFullPathName {
            get {
                return ResourceManager.GetString("TxtDynDataFullPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory usage %.
        /// </summary>
        internal static string TxtDynDataMemoryUsagePercentage {
            get {
                return ResourceManager.GetString("TxtDynDataMemoryUsagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of iterations.
        /// </summary>
        internal static string TxtDynDataNumberOfIterations {
            get {
                return ResourceManager.GetString("TxtDynDataNumberOfIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object ID.
        /// </summary>
        internal static string TxtDynDataObjectID {
            get {
                return ResourceManager.GetString("TxtDynDataObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        internal static string TxtDynDataObjectName {
            get {
                return ResourceManager.GetString("TxtDynDataObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address entered is not valid.
        /// </summary>
        internal static string TxtEMailNotValid {
            get {
                return ResourceManager.GetString("TxtEMailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an e-mail address..
        /// </summary>
        internal static string TxtEnterAnEMailAddress {
            get {
                return ResourceManager.GetString("TxtEnterAnEMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event code.
        /// </summary>
        internal static string TxtEventCode {
            get {
                return ResourceManager.GetString("TxtEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file task.
        /// </summary>
        internal static string TxtExcelFileTask {
            get {
                return ResourceManager.GetString("TxtExcelFileTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string TxtFail {
            get {
                return ResourceManager.GetString("TxtFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed backups number.
        /// </summary>
        internal static string TxtFailedBackupsNUmber {
            get {
                return ResourceManager.GetString("TxtFailedBackupsNUmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string TxtFieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("TxtFieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} must be a number between &quot;{1}&quot; and &quot;{2}&quot;.
        /// </summary>
        internal static string TxtFieldMustBeANumberBetweenXAndY {
            get {
                return ResourceManager.GetString("TxtFieldMustBeANumberBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be greater than &quot;{0}&quot;.
        /// </summary>
        internal static string TxtFieldMustBeGreaterThanX {
            get {
                return ResourceManager.GetString("TxtFieldMustBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid boolean.
        /// </summary>
        internal static string TxtFieldNotContainAValidBool {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid integer.
        /// </summary>
        internal static string TxtFieldNotContainAValidInteger {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid long.
        /// </summary>
        internal static string TxtFieldNotContainAValidLong {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid number.
        /// </summary>
        internal static string TxtFieldNotContainAValidNumber {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field doesn&apos;t contain a valid Sql Server date.
        /// </summary>
        internal static string TxtFieldNotContainAValidSqlServerDate {
            get {
                return ResourceManager.GetString("TxtFieldNotContainAValidSqlServerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system event.
        /// </summary>
        internal static string TxtFileSystemEvent {
            get {
                return ResourceManager.GetString("TxtFileSystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system task.
        /// </summary>
        internal static string TxtFileSystemTask {
            get {
                return ResourceManager.GetString("TxtFileSystemTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all rows.
        /// </summary>
        internal static string TxtFindAllRows {
            get {
                return ResourceManager.GetString("TxtFindAllRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and replace.
        /// </summary>
        internal static string TxtFindAndReplace {
            get {
                return ResourceManager.GetString("TxtFindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find first row.
        /// </summary>
        internal static string TxtFindFirstRow {
            get {
                return ResourceManager.GetString("TxtFindFirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string TxtFriday {
            get {
                return ResourceManager.GetString("TxtFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string TxtFrom {
            get {
                return ResourceManager.GetString("TxtFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP - File transfer protocol.
        /// </summary>
        internal static string TxtFTPFileTransferProtocol {
            get {
                return ResourceManager.GetString("TxtFTPFileTransferProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP / SFTP task.
        /// </summary>
        internal static string TxtFtpSftpTask {
            get {
                return ResourceManager.GetString("TxtFtpSftpTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full backup.
        /// </summary>
        internal static string TxtFullBackup {
            get {
                return ResourceManager.GetString("TxtFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        internal static string TxtGet {
            get {
                return ResourceManager.GetString("TxtGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes.
        /// </summary>
        internal static string TxtGigabytes {
            get {
                return ResourceManager.GetString("TxtGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greather than.
        /// </summary>
        internal static string TxtGreaterThan {
            get {
                return ResourceManager.GetString("TxtGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string TxtHead {
            get {
                return ResourceManager.GetString("TxtHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string TxtHigh {
            get {
                return ResourceManager.GetString("TxtHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert row.
        /// </summary>
        internal static string TxtInsertRow {
            get {
                return ResourceManager.GetString("TxtInsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string TxtInteger {
            get {
                return ResourceManager.GetString("TxtInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length / Precision.
        /// </summary>
        internal static string TxtLengthPrecision {
            get {
                return ResourceManager.GetString("TxtLengthPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string TxtLessThan {
            get {
                return ResourceManager.GetString("TxtLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string TxtLow {
            get {
                return ResourceManager.GetString("TxtLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string TxtMedium {
            get {
                return ResourceManager.GetString("TxtMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        internal static string TxtMegabytes {
            get {
                return ResourceManager.GetString("TxtMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory event.
        /// </summary>
        internal static string TxtMemoryEvent {
            get {
                return ResourceManager.GetString("TxtMemoryEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified files.
        /// </summary>
        internal static string TxtModifiedFiles {
            get {
                return ResourceManager.GetString("TxtModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string TxtMonday {
            get {
                return ResourceManager.GetString("TxtMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string TxtMove {
            get {
                return ResourceManager.GetString("TxtMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number between &quot;{0}&quot; and &quot;{1}&quot;.
        /// </summary>
        internal static string TxtMustBeANumberBetweenXAndY {
            get {
                return ResourceManager.GetString("TxtMustBeANumberBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New files.
        /// </summary>
        internal static string TxtNewFiles {
            get {
                return ResourceManager.GetString("TxtNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No header&gt;.
        /// </summary>
        internal static string TxtNoHeader {
            get {
                return ResourceManager.GetString("TxtNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No value&gt;.
        /// </summary>
        internal static string TxtNoValue {
            get {
                return ResourceManager.GetString("TxtNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TxtOptions {
            get {
                return ResourceManager.GetString("TxtOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string TxtOverwrite {
            get {
                return ResourceManager.GetString("TxtOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite archive.
        /// </summary>
        internal static string TxtOverwriteArchive {
            get {
                return ResourceManager.GetString("TxtOverwriteArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite if file exists.
        /// </summary>
        internal static string TxtOverwriteIfExists {
            get {
                return ResourceManager.GetString("TxtOverwriteIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields &quot;Password&quot; and &quot;Confirm password&quot; do not match..
        /// </summary>
        internal static string TxtPasswordAndConfirmDoNotMatch {
            get {
                return ResourceManager.GetString("TxtPasswordAndConfirmDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch.
        /// </summary>
        internal static string TxtPatch {
            get {
                return ResourceManager.GetString("TxtPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string TxtPath {
            get {
                return ResourceManager.GetString("TxtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string TxtPercentage {
            get {
                return ResourceManager.GetString("TxtPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string TxtPost {
            get {
                return ResourceManager.GetString("TxtPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put.
        /// </summary>
        internal static string TxtPut {
            get {
                return ResourceManager.GetString("TxtPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From &lt;row&gt; to last row.
        /// </summary>
        internal static string TxtReadFromRowToLastRow {
            get {
                return ResourceManager.GetString("TxtReadFromRowToLastRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From &lt;row&gt; to &lt;row&gt;.
        /// </summary>
        internal static string TxtReadFromRowToRow {
            get {
                return ResourceManager.GetString("TxtReadFromRowToRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &lt;number&gt; rows.
        /// </summary>
        internal static string TxtReadLastNRows {
            get {
                return ResourceManager.GetString("TxtReadLastNRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read row.
        /// </summary>
        internal static string TxtReadRow {
            get {
                return ResourceManager.GetString("TxtReadRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read text file task.
        /// </summary>
        internal static string TxtReadTextFileTask {
            get {
                return ResourceManager.GetString("TxtReadTextFileTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive copy.
        /// </summary>
        internal static string TxtRecursiveCopy {
            get {
                return ResourceManager.GetString("TxtRecursiveCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Api Task.
        /// </summary>
        internal static string TxtRESTApiTask {
            get {
                return ResourceManager.GetString("TxtRESTApiTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run program task.
        /// </summary>
        internal static string TxtRunProgramTask {
            get {
                return ResourceManager.GetString("TxtRunProgramTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string TxtSaturday {
            get {
                return ResourceManager.GetString("TxtSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string TxtScale {
            get {
                return ResourceManager.GetString("TxtScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale must be less than precision.
        /// </summary>
        internal static string TxtScaleMustBeLessThanPrecision {
            get {
                return ResourceManager.GetString("TxtScaleMustBeLessThanPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail task.
        /// </summary>
        internal static string TxtSendEMailTask {
            get {
                return ResourceManager.GetString("TxtSendEMailTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFTP - SSH File transfer protocol.
        /// </summary>
        internal static string TxtSFTPSSHFileTransferProtocol {
            get {
                return ResourceManager.GetString("TxtSFTPSSHFileTransferProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server backup task.
        /// </summary>
        internal static string TxtSqlServerBackupTask {
            get {
                return ResourceManager.GetString("TxtSqlServerBackupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server bulk copy task.
        /// </summary>
        internal static string TxtSqlServerBulkCopyTask {
            get {
                return ResourceManager.GetString("TxtSqlServerBulkCopyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server command task.
        /// </summary>
        internal static string TxtSqlServerCommandTask {
            get {
                return ResourceManager.GetString("TxtSqlServerCommandTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.
        /// </summary>
        internal static string TxtSqlTypeBit {
            get {
                return ResourceManager.GetString("TxtSqlTypeBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string TxtSqlTypeDate {
            get {
                return ResourceManager.GetString("TxtSqlTypeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string TxtSqlTypeDateTime {
            get {
                return ResourceManager.GetString("TxtSqlTypeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int.
        /// </summary>
        internal static string TxtSqlTypeInt {
            get {
                return ResourceManager.GetString("TxtSqlTypeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string TxtSqlTypeLong {
            get {
                return ResourceManager.GetString("TxtSqlTypeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string TxtSqlTypeNumeric {
            get {
                return ResourceManager.GetString("TxtSqlTypeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVarchar.
        /// </summary>
        internal static string TxtSqlTypeNVarchar {
            get {
                return ResourceManager.GetString("TxtSqlTypeNVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varchar.
        /// </summary>
        internal static string TxtSqlTypeVarchar {
            get {
                return ResourceManager.GetString("TxtSqlTypeVarchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string TxtSqlTypeXml {
            get {
                return ResourceManager.GetString("TxtSqlTypeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string TxtString {
            get {
                return ResourceManager.GetString("TxtString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful backups number.
        /// </summary>
        internal static string TxtSuccessfulBackupsNumber {
            get {
                return ResourceManager.GetString("TxtSuccessfulBackupsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string TxtSunday {
            get {
                return ResourceManager.GetString("TxtSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System events event.
        /// </summary>
        internal static string TxtSystemEventsEvent {
            get {
                return ResourceManager.GetString("TxtSystemEventsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDP Robot service start event.
        /// </summary>
        internal static string TxtTDPRobotServiceStartEvent {
            get {
                return ResourceManager.GetString("TxtTDPRobotServiceStartEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes.
        /// </summary>
        internal static string TxtTerabytes {
            get {
                return ResourceManager.GetString("TxtTerabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dummy Programmer Robot.
        /// </summary>
        internal static string TxtTheDummyProgrammerRobot {
            get {
                return ResourceManager.GetString("TxtTheDummyProgrammerRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors, cannot save the configuration..
        /// </summary>
        internal static string TxtThereAreSomeErrors {
            get {
                return ResourceManager.GetString("TxtThereAreSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be a number between &quot;{1}&quot; and &quot;{2}&quot;.
        /// </summary>
        internal static string TxtThisFieldMustBeANumberBetweenXAndY {
            get {
                return ResourceManager.GetString("TxtThisFieldMustBeANumberBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will overwrite your current columns definition. Do you want to continue?.
        /// </summary>
        internal static string TxtThisWillOverwriteCurrentColDef {
            get {
                return ResourceManager.GetString("TxtThisWillOverwriteCurrentColDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string TxtThursday {
            get {
                return ResourceManager.GetString("TxtThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string TxtTo {
            get {
                return ResourceManager.GetString("TxtTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction log.
        /// </summary>
        internal static string TxtTransactionLog {
            get {
                return ResourceManager.GetString("TxtTransactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TxtTuesday {
            get {
                return ResourceManager.GetString("TxtTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Sql Server.
        /// </summary>
        internal static string TxtUnableToConnectToSqlServer {
            get {
                return ResourceManager.GetString("TxtUnableToConnectToSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get database list.
        /// </summary>
        internal static string TxtUnableToGetDatabaseList {
            get {
                return ResourceManager.GetString("TxtUnableToGetDatabaseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip task.
        /// </summary>
        internal static string TxtUnzipTask {
            get {
                return ResourceManager.GetString("TxtUnzipTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use server default.
        /// </summary>
        internal static string TxtUseServerDefault {
            get {
                return ResourceManager.GetString("TxtUseServerDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string TxtWednesday {
            get {
                return ResourceManager.GetString("TxtWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write text file task.
        /// </summary>
        internal static string TxtWriteTextFileTask {
            get {
                return ResourceManager.GetString("TxtWriteTextFileTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a column.
        /// </summary>
        internal static string TxtYouMustEnterAColumn {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a column width for all columns.
        /// </summary>
        internal static string TxtYouMustEnterAColumnWidthForAll {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAColumnWidthForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a folder.
        /// </summary>
        internal static string TxtYouMustEnterAFolder {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least one field.
        /// </summary>
        internal static string TxtYouMustEnterAtLeastOneField {
            get {
                return ResourceManager.GetString("TxtYouMustEnterAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a connection string.
        /// </summary>
        internal static string TxtYouMustEnterConnectionString {
            get {
                return ResourceManager.GetString("TxtYouMustEnterConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter database credentials.
        /// </summary>
        internal static string TxtYouMustEnterDatabaseCredentials {
            get {
                return ResourceManager.GetString("TxtYouMustEnterDatabaseCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name.
        /// </summary>
        internal static string TxtYouMustEnterName {
            get {
                return ResourceManager.GetString("TxtYouMustEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must insert a value or check &quot;Pass NULL value&quot;.
        /// </summary>
        internal static string TxtYouMustInsertValueOrNull {
            get {
                return ResourceManager.GetString("TxtYouMustInsertValueOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a database.
        /// </summary>
        internal static string TxtYouMustSelectADatabase {
            get {
                return ResourceManager.GetString("TxtYouMustSelectADatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a delimiter.
        /// </summary>
        internal static string TxtYouMustSelectADelimiter {
            get {
                return ResourceManager.GetString("TxtYouMustSelectADelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an event.
        /// </summary>
        internal static string TxtYouMustSelectAnEvent {
            get {
                return ResourceManager.GetString("TxtYouMustSelectAnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a type.
        /// </summary>
        internal static string TxtYouMustSelectAType {
            get {
                return ResourceManager.GetString("TxtYouMustSelectAType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an item..
        /// </summary>
        internal static string TxtYouMustSelectItem {
            get {
                return ResourceManager.GetString("TxtYouMustSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a custom delimiter.
        /// </summary>
        internal static string TxtYouMustSpecifyACustomDelimiter {
            get {
                return ResourceManager.GetString("TxtYouMustSpecifyACustomDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip task.
        /// </summary>
        internal static string TxtZipTask {
            get {
                return ResourceManager.GetString("TxtZipTask", resourceCulture);
            }
        }
    }
}
